### ISSUE TITLE
КриптоПро импорт PFX файл ошибка "Algorithm not supported"

### ISSUE THREAD

**Issue by romstyop** [rudonick/crypto#12]
Создал  здесь https://www.cryptopro.ru/certsrv/certrqma.asp сертификат 34.10-2012 CSP
Установил его.
Протестировал на C# через CryptoPro.NET, работает.

Попытался на демо http://gostcrypto.com/demo-cp-keys.html
импортировать pfx файл с приватным ключом, выдает ошибку  "Algorithm not supported".
В ASN.1 Data вижу вот такую строку  OBJECT IDENTIFIER pbeUnknownGost (1.2.840.113549.1.12.1.80)

**Comment by romstyop** [comment]
Разобрался. Сам КриптоПро это не позволяет делать

**Comment by evgeniy-kolupaev** [comment]
@romstyop Можно подробней, почему не позволяет? Можно ли, имея такой PFX, подписывать данные с помощью этой библиотеки?
