### ISSUE TITLE
Не работает экспорт из КриптоПро Контейнера ГОСТ 2012

### ISSUE THREAD

**Issue by svkreml** [rudonick/crypto#14]
Do not work "exportPrivateKey()" on page http://gostcrypto.com/demo-cp-keys.html for ГОСТ 2012 
error on line: 
               if (!equalBuffers(hmac, self.header.hmacKeyContainerContent))
                        throw new Error("Container is not valid.");
key from https://testca2012.cryptopro.ru/ui/ 
[le-d3bb8.000.zip](https://github.com/rudonick/crypto/files/2185343/le-d3bb8.000.zip) password qwerty
on pressing "Export Key and Certificate"
![image](https://user-images.githubusercontent.com/7316441/42586135-0dee4de8-8540-11e8-96e0-f7e52009b3d3.png)

**Comment by garex** [comment]
May be issue is similar to ours: see fixes in this merge commit: https://github.com/garex/nodejs-gost-crypto/tree/561a78fb1a5a9a92f089209002692374bce48d7c

There were wrong assumptions that all keys has same length.

**Comment by state13** [comment]
@garex I am still getting "Container is not valid" error. I think something is wrong with key-mac calculation. SignalCom exporting is working now though, thanx again for that.

**Comment by garex** [comment]
@state13 but nobody fixed those ))

I just think the issue there is similar — keys size (assumed 256, but actually has 512).

**Comment by garex** [comment]
@state13 fixed in https://github.com/garex/nodejs-gost-crypto/commit/180341fdfd63f91b6f3c3ba374bda6bd5996d5fd

Added cli tool for this.

```
sudo npm install -g https://github.com/garex/nodejs-gost-crypto/archive/nodefy.tar.gz
cd path-to-your-keys
gost-export-cryptopro-key
```

See `gost-export-cryptopro-key -h` for other options:

```
Usage:
  gost-export-cryptopro-key [OPTIONS]

Options: 
  -c, --container [DIRECTORY] Path to directory with container files "header.key", "name.key", "primary.key", "masks.key", 
                              "primary2.key", "masks2.key"  (Default is .)
  -p, --password STRING       Private key`s password in case if encypted
  -f, --format [VALUE]        Export format. VALUE must be either [PEM|DER] (Default is PEM)
  -s, --secondary BOOLEAN     Extract from secondary keys
  -v, --version               Display the current version
  -h, --help                  Display help and usage details
```

**Comment by svkreml** [comment]
Looks Like all Works. Thanks

**Comment by state13** [comment]
@garex Thanks. Actually I have found by myself that E-Z sBox has to be used with new CryptoPro container instead of default E-A. I even thinking to create pull request. But I am not sure though that E-Z could be used with all scope of tc26 algorithms.

**Comment by garex** [comment]
@state13 as I understand, it's a default now by standard. In decompiled cryptocom jar it called DEFAULT constant.

**Comment by Hiller** [comment]
@garex Seems like it's not working again. When i'm trying to export key i'm getting "Icorrect fp" error.
here's sample https://yadi.sk/d/Q4ioGumuLDXRDw key password is 123456
