### ISSUE TITLE
Export SignalCom GOST 2012 key not working

### ISSUE THREAD

**Issue by state13** [rudonick/crypto#15]
Hello,

I am getting 'Invalid key MAC' error message when exporting SignalCom GOST 2012 key on this page http://gostcrypto.com/demo-sc-keys.html

**Comment by DmitryRomanov** [comment]
+1

**Comment by garex** [comment]
Fixed in https://github.com/garex/nodejs-gost-crypto/tree/561a78fb1a5a9a92f089209002692374bce48d7c

**Comment by state13** [comment]
@garex Thank you!
