### ISSUE TITLE
How to get correct signature

### ISSUE THREAD

**Issue by wingedfox** [rudonick/crypto#3]
Hi,

I'm trying to sign string using gostcrypt, but it does not work as expected. Here is an example:

``` js
const SIGNATURE = gostEngine.getGostSign({
    name: 'GOST R 34.10',
    version: 2001
});
const KEY = gostCoding.PEM.decode(signingKey.exchangeKey);

let res = SIGNATURE.sign(KEY, new Buffer(textString));
```

The problem is that that I can't verify the signature using CryptoPro tools.

They private key is taken from the CryptoPro container and CryptoPro builds correct signature for the same text.

``` bash
csptest -keyset -sign GOST -in text -out text.bin -container '\\.\HDIMAGE\TEST' -keytype exchange
```

Is there anything I can tweak in the code to make valid (recognizable) signature?

**Comment by wingedfox** [comment]
Got it, `exchange` key used for signing requires `X-256-A` curve, not the default `S-256-A`.

**Comment by rudonick** [comment]
Yes, you are right. But it only for csptest. In other cases parameters of curve can be different. Real ASN.1 CMS message has clear definition of curve parameters.
