### ISSUE TITLE
Load CryptoPro public.cer: gost.cert.X509(cer) - Error: Algorithm not supported

### ISSUE THREAD

**Issue by romansopov** [rudonick/crypto#4]
Do not load the public certificate CryptoPro. I want to make signature CMS.
http://gostcrypto.com/pki-sign.html

Why is it not working?

-----BEGIN CERTIFICATE-----
MIIHFjCCBsWgAwIBAgIKTMUyyAAAAAADVDAIBgYqhQMCAgMwggFGMRgwFgYFKoUD
ZAESDTEyMzQ1Njc4OTAxMjMxGjAYBggqhQMDgQMBARIMMDAxMjM0NTY3ODkwMSkw
JwYDVQQJDCDQodGD0YnQtdCy0YHQutC40Lkg0LLQsNC7INC0LiAyNjEXMBUGCSqG
SIb3DQEJARYIY2FAcnQucnUxCzAJBgNVBAYTAlJVMRgwFgYDVQQIDA83NyDQnNC+
0YHQutCy0LAxFTATBgNVBAcMDNCc0L7RgdC60LLQsDEkMCIGA1UECgwb0J7QkNCe
INCg0L7RgdGC0LXQu9C10LrQvtC8MTAwLgYDVQQLDCfQo9C00L7RgdGC0L7QstC1
0YDRj9GO0YnQuNC5INGG0LXQvdGC0YAxNDAyBgNVBAMMK9Ci0LXRgdGC0L7QstGL
0Lkg0KPQpiDQoNCi0JogKNCg0KLQm9Cw0LHRgSkwHhcNMTYwNTE2MDYzODAwWhcN
MTcwNTE2MDY0ODAwWjCBxTEYMBYGBSqFA2QBEg0xMDk3NzQ2NDA1Nzc4MRowGAYI
KoUDA4EDAQESDDAwNzcyMDY2MzM0MDELMAkGA1UEBhMCUlUxGzAZBgNVBAgeEgA3
ADcAIAQcBD4EQQQ6BDIEMDEVMBMGA1UEBx4MBBwEPgRBBDoEMgQwMSkwJwYDVQQK
HiAEHgQeBB4AIACrBCEEHgQaBB4AIAQTBEAEQwQ/BD8AuzEhMB8GA1UEAx4YAEIA
YQBuAGsAQQBQAEkAIAQhBBwELQQSMGMwHAYGKoUDAgITMBIGByqFAwICJAAGByqF
AwICHgEDQwAEQJELiGAiQWONeWaHl7teYB7otIhWfOteSINqhQfcRbfq7tCRo3Bq
MVzm21f59w++C3CcR4oy7A8lXJgaSbMEEDqjggQPMIIECzAOBgNVHQ8BAf8EBAMC
BPAwJgYDVR0lBB8wHQYIKwYBBQUHAwQGByqFAwICIgYGCCsGAQUFBwMCMB0GA1Ud
DgQWBBQHaa7OM0HilZl9ASZvnxZataaD+zCCAYcGA1UdIwSCAX4wggF6gBRBsswy
nDh/Lf2MhhVYI2IKd/Us/6GCAU6kggFKMIIBRjEYMBYGBSqFA2QBEg0xMjM0NTY3
ODkwMTIzMRowGAYIKoUDA4EDAQESDDAwMTIzNDU2Nzg5MDEpMCcGA1UECQwg0KHR
g9GJ0LXQstGB0LrQuNC5INCy0LDQuyDQtC4gMjYxFzAVBgkqhkiG9w0BCQEWCGNh
QHJ0LnJ1MQswCQYDVQQGEwJSVTEYMBYGA1UECAwPNzcg0JzQvtGB0LrQstCwMRUw
EwYDVQQHDAzQnNC+0YHQutCy0LAxJDAiBgNVBAoMG9Ce0JDQniDQoNC+0YHRgtC1
0LvQtdC60L7QvDEwMC4GA1UECwwn0KPQtNC+0YHRgtC+0LLQtdGA0Y/RjtGJ0LjQ
uSDRhtC10L3RgtGAMTQwMgYDVQQDDCvQotC10YHRgtC+0LLRi9C5INCj0KYg0KDQ
otCaICjQoNCi0JvQsNCx0YEpghADrsxomk54tEIvZVLuBT+DMGgGA1UdHwRhMF8w
XaBboFmGV2h0dHA6Ly9jZXJ0ZW5yb2xsLnRlc3QuZ29zdXNsdWdpLnJ1L3JhL2Nk
cC80MWIyY2MzMjljMzg3ZjJkZmQ4Yzg2MTU1ODIzNjIwYTc3ZjUyY2ZmLmNybDBZ
BggrBgEFBQcBAQRNMEswSQYIKwYBBQUHMAKGPWh0dHA6Ly9jZXJ0ZW5yb2xsLnRl
c3QuZ29zdXNsdWdpLnJ1L3JhL2NkcC90ZXN0X2NhX3J0bGFicy5jZXIwNgYFKoUD
ZG8ELQwrItCa0YDQuNC/0YLQvtCf0YDQviBDU1AiICjQstC10YDRgdC40Y8gMy42
KTArBgNVHRAEJDAigA8yMDE2MDUxNjA2MzgwMFqBDzIwMTcwNTE2MDYzODAwWjAd
BgNVHSAEFjAUMAgGBiqFA2RxATAIBgYqhQNkcQIwgd0GBSqFA2RwBIHTMIHQDCsi
0JrRgNC40L/RgtC+0J/RgNC+IENTUCIgKNCy0LXRgNGB0LjRjyAzLjYpDFMi0KPQ
tNC+0YHRgtC+0LLQtdGA0Y/RjtGJ0LjQuSDRhtC10L3RgtGAICLQmtGA0LjQv9GC
0L7Qn9GA0L4g0KPQpiIg0LLQtdGA0YHQuNC4IDEuNQwl4oSWINCh0KQvMTI0LTIy
Mzgg0L7RgiAwNC4xMC4yMDEzINCzLgwl4oSWINCh0KQvMTI4LTIzNTIg0L7RgiAx
NS4wNC4yMDE0INCzLjAIBgYqhQMCAgMDQQAaiJ8c6cMj4OcmFYLeyIUitqH1J9Ic
OETy8R1L83saJlIXpt9gKtGfgcFZEfRaIGCYkxBAwJcv9KTLHhbG/Vm4
-----END CERTIFICATE-----

**Comment by rudonick** [comment]
Прошу прощения за долгий ответ, не было доступа к почте. Этот сертификат в
библиотеке не проходит проверку на синтаксис X.509. Взял на проверку.
Возможно ошибка в библиотеке. Результат напишу чуть позже.

Спасибо, Рудольф.

**Comment by rudonick** [comment]
It is not a bug. I don't have purpose to provide service for GOST qualified digital signature. But for any cases. 

Look to FSB order #795 (http://www.garant.ru/products/ipo/prime/doc/70033464/) and you can find plague mistake. In according to X.509 spec and in that doc the type of certificate attributes defined as

DirectoryString ::= CHOICE {
    teletexString          TeletexString (SIZE (1 ..MAX)),
    printableString        PrintableString (SIZE (1 ..MAX)),
    universalString        UniversalString (SIZE (1. .MAX)),
    utf8String             UTF8String (SIZE (1 ..MAX)),
    bmpString              BMPString (SIZE (1..MAX))}.

But below you can find description of 3 NumberString attributes: INN, OGRN and SNILS. 

For support of GOST qualified certificates in latest version I add NumericString to DirectoryString choice. Also I add syntax for issuerSignTool and subjectSignTool extension attributes.

Rudolf.
