### ISSUE TITLE
Ошибка хэш-кода

### ISSUE THREAD

**Issue by AcellaEDU** [rudonick/crypto#7]
Здравствуйте. Кажется обнаружил ошибку работы библиотеки.

**Суть ошибки:** Не выполняется условие `H(M) = H(D(E(M)))`, где `M` - сообщение; `H` - хэш-функция ГОСТ Р 34.11-2012; `E/D` - шифрование/дешифрования по алгоритму ГОСТ Р 34.12.2015 **CBC**.

В режиме OFB, условие выполняется!
Ниже приведен снимок экрана, и программный стенд на котором можно посмотреть - NetBeans.
![screenshot](https://cloud.githubusercontent.com/assets/6829626/19816183/e2cba526-9d78-11e6-9585-d75b7f82b897.png)
[AcoCryptJS.zip](https://github.com/rudonick/crypto/files/559008/AcoCryptJS.zip)

**Comment by rudonick** [comment]
Добрый день. 

Это не ошибка, это свойство режима CBC. Условие будет выполняться для CBC только если длина сообщения M кратна длине блока 64 или 128 бит - в зависимости от алгоритма шифрования. В противном случае преобразование D(E(M)) возвращает сообещние M' с дополненными нулями справа - в соответсии со стандартом ZERO PADDING. Тогда H(M) != H(M')

В OFB дополнения нет NO PADDING. Соответственно для него верно M = D(E(M)). 

Подробности читайте здесь http://tc26.ru/standard/gost/GOST_R_3413-2015.pdf

**Comment by AcellaEDU** [comment]
Спасибо. За ответ.)
